runtime: nodejs8

# what follows will be optional in the future:
threadsafe: true
handlers:
- url: /.*
  script: server.js
  # login: required
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^.*node_modules(/.*)?
